# Generated by Django 5.0.4 on 2024-05-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BazaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('cena', models.FloatField()),
                ('dostepne', models.BooleanField(default=False)),
                ('adres', models.CharField(max_length=100)),
            ],
        ),
    ]
