# Generated by Django 5.0.4 on 2024-05-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bazaitem',
            name='opis',
            field=models.CharField(default='123', max_length=100),
        ),
    ]
